import { RouteName } from '../types';

/**
 * set "crudRoute" metadata that contains operation and method
 * used to mark a method as a crud route to add crud metadata similar to the default methods that generated by \@Crud()
 * such as adding Swagger docs metadata
 *
 * @param operation
 * @param path
 * @example \@CrudRoute("getOne", "/me")
 */
export const CrudRoute =
  (operation: RouteName, path: string) =>
  (target: Object, method: string, descriptor: PropertyDescriptor) => {
    // or Reflect.defineMetadata("crudRoute", {...}, target, method)
    Reflect.defineMetadata('crudRoute', { operation, path }, descriptor.value);
    return descriptor;
  };
